# Generated by Django 3.1.1 on 2021-02-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('Allocation', 'Allocation'), ('Project', 'Project'), ('FrontEnd', 'Front End'), ('Api', 'API')], default='Project', max_length=23)),
                ('name', models.CharField(max_length=61)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'log_type')},
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('GR', 'General'), ('LI', 'Login'), ('SC', 'Request Status Change'), ('PR', 'Product Provision'), ('EF', 'Form Update')], default='GR', max_length=2)),
                ('name', models.CharField(max_length=61)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='CramsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('before_json_data', models.TextField(blank=True, null=True)),
                ('after_json_data', models.TextField(blank=True, null=True)),
                ('creation_ts', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=99, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crams_log.logaction')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crams_log.logtype')),
            ],
        ),
    ]
