# Generated by Django 3.2.4 on 2021-07-21 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crams', '0011_softwarelicensestatus'),
        ('crams_allocation', '0002_init_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='contact_license_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crams.softwarelicensestatus'),
        ),
    ]
