# Generated by Django 3.2 on 2021-07-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crams', '0009_projectmemberstatus'),
        ('crams_allocation', '0002_init_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='project_member_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crams.projectmemberstatus'),
        ),
    ]
