INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Computational', (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 1, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 307.71, 726.53, null, 448000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Market-File',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 3, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 298.91, 734.02, null, 2642000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Market-SONAS',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 3, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 298.91, 734.03, null, 372000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Vault',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 3, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 154.20, 214.13, null, 4050000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Object',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 2, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 298.91, 734.02, null, 640000);

insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Submitted', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'X'), 1);
insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Declined', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'J'), 1);
insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Approved', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'A'), 1);
insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Provisioned', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'P'), 1);
