INSERT INTO crams_fundingbody (`name`, email) VALUES ('CRAMS', 'crams@crams.com');
INSERT INTO crams_fundingscheme (funding_scheme, funding_body_id) VALUES ('CRAMS-FS', (SELECT id from crams_fundingbody where `name` = 'CRAMS'));
INSERT INTO crams_eresearchbody (`name`, email) VALUES ('CRAMS-ERB', 'crams@crams.com');
INSERT INTO crams_eresearchbodysystem (e_research_body_id, `name`) VALUES ((SELECT id from crams_eresearchbody where `name` = 'CRAMS-ERB'), 'CRAMS-ERB-SYS');
INSERT INTO crams_eresearchbodyidkey (`key`, e_research_body_id, `type`) VALUES ('CRAMS',(SELECT id from crams_eresearchbody where `name` = 'CRAMS-ERB'), 'I');
INSERT INTO crams_provider (id, `name`, active,  created_by_id, creation_ts, description, last_modified_ts, start_date, updated_by_id) VALUES (1, 'CRAMS', true, NULL, '2021-02-25 16:33:18.000000', NULL, '2021-02-25 16:33:18.000000', '2021-02-25', NULL);

INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Computational', (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 1, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 307.71, 726.53, null, 448000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Market-File',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 3, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 298.91, 734.02, null, 2642000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Market-SONAS',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 3, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 298.91, 734.03, null, 372000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Vault',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 3, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 154.20, 214.13, null, 4050000);
INSERT INTO crams_storage_storageproduct (`name`, funding_body_id, provider_id, storage_type_id, zone_id, e_research_system_id, operational_cost, unit_cost, cost_unit_type_id, capacity) VALUES ('Object',  (SELECT id from crams_fundingbody where `name` = 'CRAMS'), 1, 2, NULL, (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), 298.91, 734.02, null, 640000);

insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Submitted', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'X'), 1);
insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Declined', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'J'), 1);
insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Approved', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'A'), 1);
insert into crams_allocation_erbrequeststatus(display_name, e_research_system_id, request_status_id, extension_count_data_point) values('Extension Provisioned', (SELECT id from crams_eresearchbodysystem where `name` = 'CRAMS-ERB-SYS'), (SELECT id from crams_allocation_requeststatus where code = 'P'), 1);
