# Generated by Django 3.1.1 on 2021-03-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crams_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crams_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
