# Generated by Django 3.1.1 on 2020-11-20 00:54

from django.db import migrations


def load_crams_collection_inital_data_from_sql():
    import os

    file_name = 'initial_collection.sql'
    sql_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sql_dir, file_name), 'r').read()

    return sql_statements


class Migration(migrations.Migration):
    dependencies = [
        ('crams_collection', '0002_project_crams_id'),
    ]

    operations = [
        migrations.RunSQL(load_crams_collection_inital_data_from_sql()),
    ]
