# Generated by Django 3.1.1 on 2021-03-11 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crams_log', '0001_initial'),
        ('crams_collection', '0003_init_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crams_project_db_id', models.IntegerField()),
                ('log_parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projectlog', to='crams_log.cramslog')),
            ],
            options={
                'unique_together': {('crams_project_db_id', 'log_parent')},
            },
        ),
    ]
