# Generated by Django 3.1.1 on 2021-03-16 03:37
import os

from django.db import migrations


def load_demo_initial_data_from_sql():
    file_name = 'crams_demo_initial.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()

    return sql_statements


def load_demo_compute_data_from_sql():
    file_name = 'crams_demo_compute_products.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()

    return sql_statements


def load_contact_roles_data_from_sql():
    file_name = 'crams_demo_contact_roles.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()

    return sql_statements


def load_demo_questions_from_sql():
    file_name = 'crams_demo_questions.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()

    return sql_statements


def load_support_email_sql():
    file_name = 'support_email.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()

    return sql_statements


def load_email_notification_sql():
    file_name = 'email_notifcation_templetes.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()
    return sql_statements


def load_member_notification_sql():
    file_name = 'member_notification_templates.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()
    return sql_statements


def load_demo_org_faculty_data_sql():
    file_name = 'crams_demo_org_faculty_dept.mysql.sql'
    sqls_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../sqls'))
    sql_statements = open(os.path.join(sqls_dir, file_name), 'r').read()
    return sql_statements


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunSQL(load_demo_initial_data_from_sql()),
        migrations.RunSQL(load_contact_roles_data_from_sql()),
        migrations.RunSQL(load_demo_compute_data_from_sql()),
        migrations.RunSQL(load_demo_questions_from_sql()),
        migrations.RunSQL(load_support_email_sql()),
        migrations.RunSQL(load_demo_org_faculty_data_sql()),
        migrations.RunSQL(load_email_notification_sql()),
        migrations.RunSQL(load_member_notification_sql()),
    ]
