# Configurable fields for Software Products
# from crams.common.constants import db

# TODO: refactor this into the config erb module
eRESEARCH_BODY_HPC = 'HPC'
HPC_POSIX_USERID = 'HPC_POSIX_USER_ID'
HPC_SOFTWARE_GROUP_ID = 'HPC_SOFTWARE_GROUP_ID'

ERB_CONTACT_ID_KEY = dict()
ERB_CONTACT_ID_KEY[eRESEARCH_BODY_HPC] = HPC_POSIX_USERID

ERB_SOFTWARE_GROUP_ID_KEY = dict()
ERB_SOFTWARE_GROUP_ID_KEY[eRESEARCH_BODY_HPC] = HPC_SOFTWARE_GROUP_ID
