# Generated by Django 3.1.1 on 2021-03-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crams', '0008_load_crams_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_cost', models.FloatField(default=0.0)),
                ('operational_cost', models.FloatField(default=0.0)),
                ('capacity', models.FloatField(default=0.0)),
                ('cost_unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='computeproduct', to='crams.costunittype')),
                ('e_research_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='computeproduct', to='crams.eresearchbodysystem')),
                ('funding_body', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computeproduct', to='crams.fundingbody')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computeproduct', to='crams.provider')),
            ],
            options={
                'unique_together': {('name', 'e_research_system')},
                'index_together': {('name', 'e_research_system')},
            },
        ),
        migrations.CreateModel(
            name='ComputeProductProvisionId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_id', models.CharField(blank=True, max_length=255, null=True)),
                ('compute_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crams_compute.computeproduct')),
            ],
            options={
                'unique_together': {('provision_id', 'compute_product')},
                'index_together': {('provision_id', 'compute_product')},
            },
        ),
    ]
